server:
  port: 8084

spring:
  codec:
    max-in-memory-size: 1MB
  application:
    name: ruleshake-samples
  webflux:
    base-path: /api

ruleshake:
  referential:
    base-path: ${REFERENTIAL_URL:http://localhost:8083/api}
    timeout: 1s
  runner:
    base-path: ${RUNNER_URL:http://localhost:8082/api}
    timeout: 1s
  auth:
    url: ${RULESHAKE_SAMPLES_AUTH_URL}
    audience: ${RULESHAKE_SAMPLES_AUTH_AUDIENCE}
    client-id: ${RULESHAKE_SAMPLES_AUTH_CLIENT_ID}
    client-secret: ${RULESHAKE_SAMPLES_AUTH_CLIENT_SECRET}
