name: "Setup maven environment"
description: "Setup maven environment"
inputs:
  github-deps-token:
    required: true
    description: "Github Personal Access Token to install dependencies from Github Packages"
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Maven settings
      uses: s4u/maven-settings-action@v2.7.0
      with:
        servers: |
          [{
            "id": "github",
            "username": "dummy",
            "password": "${{ github.token }}"
          },
          {
            "id": "github-deps",
            "username": "dummy",
            "password": "${{ inputs.github-deps-token }}"
          }]
        githubServer: false