name: Main workflow

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./back

jobs:
  publish-app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/maven-setup
        with:
          github-deps-token: ${{ secrets.GH_PAT_FOR_ACTIONS_TOKEN }}
      - name: Build project
        run: mvn -B install
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          provenance: false
          tags: |
            ghcr.io/ruleshake/samples:develop
          labels: |
            org.opencontainers.image.title=ruleshake-samples
            org.opencontainers.image.authors=Mohammed BOUKADA
            org.opencontainers.image.version=develop
            org.opencontainers.image.created=${{ github.event.repository.updated_at}}
            org.opencontainers.image.revision=${{ github.sha }}
