name: Main workflow

on:
  push:
    branches: [ main ]

jobs:
  opensource-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
  code-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=high
  build:
    runs-on: ubuntu-latest
    needs: [opensource-security, code-security]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/maven-setup
        with:
          github-deps-token: ${{ secrets.GH_PAT_FOR_ACTIONS_TOKEN }}
      - name: Build and test with Maven
        run: mvn -B package
  publish-lib:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/maven-setup
        with:
          github-deps-token: ${{ secrets.GH_PAT_FOR_ACTIONS_TOKEN }}
      - name: Publish to GitHub Packages
        run: cd runner-client && mvn -B deploy -DskipTests
  publish-app:
    runs-on: ubuntu-latest
    needs: publish-lib
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/maven-setup
        with:
          github-deps-token: ${{ secrets.GH_PAT_FOR_ACTIONS_TOKEN }}
      - name: Build project
        run: mvn -B install -DskipTests
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
