name: Pull request workflow

on:
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./back

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/maven-setup
        with:
          github-deps-token: ${{ secrets.GH_PAT_FOR_ACTIONS_TOKEN }}
      - name: Build and test with Maven
        run: mvn -B test

